import type { Metadata } from "next";
import "./globals.css";
import Sider from "./component/sider/sider";
import Header from "./component/header/header";
import { MainComponent } from "./component/layout/layout";



export const metadata: Metadata = {
  title: "Home Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex ">
        <Sider />
        <div className="flex flex-col">
          <Header />
          <main>
            <MainComponent children={children} />
          </main>
        </div>
      </body>
    </html>
  );
}
