import type { Metadata } from "next";
import "./globals.css";
import Sider from "./component/sider/sider";
import Header from "./component/header/header";



export const metadata: Metadata = {
  title: "Home Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex ">
        <Sider/>
        <div className="flex flex-col">
          <Header/>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
